import { buildActionTypes } from '../helpers'

const types = [
  'ADD_NOTIFICATION',
  'REMOVE_NOTIFICATION',
  'GET_CONTAINERS',
  'GET_CONTAINERS_SUCESS',
  'START_CONTAINER',
  'START_CONTAINER_SUCESS',
  'STOP_CONTAINER',
  'STOP_CONTAINER_SUCESS',
  'DELETE_CONTAINER',
  'DELETE_CONTAINER_SUCESS',
  'CREATE_CONTAINER',
  'CREATE_CONTAINER_SUCESS',
  'GET_CONTAINER_STATS',
  'GET_CONTAINER_STATS_SUCESS',
  'GET_CONTAINER_LOG',
  'GET_CONTAINER_LOG_SUCESS',
  'CLEAR_MONITOR',
  'UPDATE_STATS',
  'UPDATE_LOG',
  'DISCONNECT_FROM_CONTAINER',
  'CONNECT_TO_CONTAINER',
  'OUTPUT',
  'CLEAR_OUTPUT',
  'BUILD_IMAGE'
]

const objTypes = buildActionTypes(types)

export default objTypes
